Feedback360/Controllers/FeedBackScheduleController.cs
using Microsoft.AspNetCore.Mvc;
using BusinessFeedback360.DTOModels.FeedBackScheduleDetails;
using BusinessFeedback360;
using BusinessFeedback360.DTOModels.FeedBackScheduleDetails;
using System.Linq;
using RepoFeedback360.Model;
using BusinessFeedback360.DTOModels;

namespace Feedback360.Controllers
{
    public class FeedBackScheduleController : Controller
    {
        private FeedBackScheduleBL feedBackScheduleBL = null;

        [HttpGet]
        public IActionResult FeedBackSchedule()
        {
            feedBackScheduleBL= new FeedBackScheduleBL();
            ViewBag.FeedBackCatagories= feedBackScheduleBL.GetFeedbackCatagories();
            ViewBag.GetALLUser=feedBackScheduleBL.Users();
            return View();
        }
        [HttpPost]
        public IActionResult FeedBackSchedule(FeedBackScheduleDetails objScheduleDetails)
        {
            feedBackScheduleBL = new FeedBackScheduleBL();
            ViewBag.FeedBackCatagories = feedBackScheduleBL.GetFeedbackCatagories();
            ViewBag.GetALLUser = feedBackScheduleBL.Users();
            var result=feedBackScheduleBL.SetFeedbackSchedulersBL(objScheduleDetails);
            if (result) ViewData["Success"] = "FeedBackSchedule Successfully done .";
            else ViewData["Failed"] = "Some Error occures while Scheduling.";
            return View(objScheduleDetails);
        }
        [HttpGet]
        public IActionResult Candidate_List()
        {
            List<ScheduledCandidatesDL> lstCandidates = null;
            feedBackScheduleBL = new FeedBackScheduleBL();
            lstCandidates = feedBackScheduleBL.Candidate_List();
         return View(lstCandidates);
        }

        [HttpGet]
        public IActionResult ProvideFeedBack(InputData objdata)
        {
            
            TempData["EmployeeId_To"] = objdata.EmployeeId_To;
            TempData["EmployeeId_By"] = objdata.EmployeeId_By;
            TempData["DesignationId"] = objdata.DesignationId;
            feedBackScheduleBL = new FeedBackScheduleBL();
             ViewBag.AllQuestions= feedBackScheduleBL.GetAllQuestions(objdata);
             
            return View(new FEEDBACKRATINGS());
        }
        [HttpPost]
        public IActionResult ProvideFeedBack(FEEDBACKRATINGS objFeedBAckRatings,string Q_ID_1, int Rating_1,
            string Q_ID_2, int Rating_2, string Q_ID_3, int Rating_3, string Q_ID_4, int Rating_4, string Q_ID_5,int Rating_5)
        {
            List<FEEDBACKRATINGS> lstFeedbackRatings = new List<FEEDBACKRATINGS>()
            {
              new FEEDBACKRATINGS() { TOID_EmplyeeId= TempData.ContainsKey("EmployeeId_To")?TempData["EmployeeId_To"].ToString():null, BYID_EmplyeeId = TempData.ContainsKey("EmployeeId_By")?TempData["EmployeeId_By"].ToString():null,
                CreatedDate = DateTime.Now, Q_ID= Convert.ToInt16(Q_ID_1),Ratings=Rating_1
              },
              new FEEDBACKRATINGS() { TOID_EmplyeeId= TempData.ContainsKey("EmployeeId_To")?TempData["EmployeeId_To"].ToString():null, BYID_EmplyeeId = TempData.ContainsKey("EmployeeId_By")?TempData["EmployeeId_By"].ToString():null,
                CreatedDate = DateTime.Now, Q_ID= Convert.ToInt16(Q_ID_2),Ratings=Rating_2
              },
              new FEEDBACKRATINGS() { TOID_EmplyeeId= TempData.ContainsKey("EmployeeId_To")?TempData["EmployeeId_To"].ToString():null, BYID_EmplyeeId = TempData.ContainsKey("EmployeeId_By")?TempData["EmployeeId_By"].ToString():null,
                CreatedDate = DateTime.Now, Q_ID= Convert.ToInt16(Q_ID_3),Ratings=Rating_3
              },
              new FEEDBACKRATINGS() { TOID_EmplyeeId= TempData.ContainsKey("EmployeeId_To")?TempData["EmployeeId_To"].ToString():null, BYID_EmplyeeId = TempData.ContainsKey("EmployeeId_By")?TempData["EmployeeId_By"].ToString():null,
                CreatedDate = DateTime.Now, Q_ID= Convert.ToInt16(Q_ID_4),Ratings=Rating_4
              },
              new FEEDBACKRATINGS() { TOID_EmplyeeId= TempData.ContainsKey("EmployeeId_To")?TempData["EmployeeId_To"].ToString():null, BYID_EmplyeeId = TempData.ContainsKey("EmployeeId_By")?TempData["EmployeeId_By"].ToString():null,
                CreatedDate = DateTime.Now, Q_ID= Convert.ToInt16(Q_ID_5),Ratings=Rating_5
              },
            };
            feedBackScheduleBL = new FeedBackScheduleBL();
            bool status = feedBackScheduleBL.SaveFeedBAck(lstFeedbackRatings);
            if (status) return RedirectToAction("Candidate_List");
            else
            {
                ViewData["Error"] = "Save Failed";
                return View(new FEEDBACKRATINGS());
            }


        }
    }
}

Feedback360/Controllers/PasswordController.cs
using Microsoft.AspNetCore.Mvc;
using BusinessFeedback360.DTOModels.Password;
using BusinessFeedback360.DTOModels;
using BusinessFeedback360;

namespace Feedback360.Controllers
{
    public class PasswordController : Controller
    {
        private LogIn_BL _logInBl;
        public PasswordController()
        {
            this._logInBl = new LogIn_BL();
        }
        [HttpGet]
        public IActionResult ChangePassword()
        {
            ChangePasswordVM objCPVM = new ChangePasswordVM();
            objCPVM.User_Id = HttpContext.Session.GetString("_sessionUserid");
            return View(objCPVM);
        }

        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordVM objCPVM)
        {
            objCPVM.User_Id = HttpContext.Session.GetString("_sessionUserid");
            bool changepasswordStatus = _logInBl.ResetPassword_Bl(objCPVM);
            if (changepasswordStatus)
            {
                ViewData["ChangepasswordStatus"] = "Password chaged successfully";
            }
            else
            {
                ViewData["ChangepasswordStatusfailed"] = "Error While Reset the password";
            }

            return View(objCPVM);
        }

        [HttpGet]
        public IActionResult ForgotPassword()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ForgotPassword(ForgotPasswordVMDTO forgotPasswordVMDTO)
        {
            if (_logInBl.checkOtp(forgotPasswordVMDTO))
            {
                bool reset_Status = _logInBl.ResetPassword_Bl(new ChangePasswordVM
                {
                    NewPassword = forgotPasswordVMDTO.NewPassword,
                    User_Id = forgotPasswordVMDTO.UserId,
                    OldPassword = null
                });
                if (reset_Status) { TempData["SucessStatus"] = "Password Reset Successfully."; }
            }
            else
            {
                TempData["FailedStatus"] = "Otp Is InValid! or Otp session timeOut.";
            }
            return View();
        }
        [HttpPost]
        public IActionResult sendOTP(ForgotPasswordVMDTO forgotPasswordVMDTO)
        {
            bool status = false;
           
            int otpstatus =_logInBl.sendOtp(forgotPasswordVMDTO.UserId);
            //HttpContext.Session.SetString("OTP_Value",otpstatus.ToString());

            if ( otpstatus != 0 ? status = true : false)
            {
                TempData["SucessStatus"] = "Sucessfully sent otp on resistered Email";
            }
            else
            {
                TempData["FailedStatus"] = "Couldn't Send Otp Try again .";
            }
            return View("ForgotPassword");
        }
    }
}

Feedback360/Controllers/UserManagementController.cs
using Microsoft.AspNetCore.Mvc;
using BusinessFeedback360;
using RepoFeedback360.Model;
using BusinessFeedback360.DTOModels;

namespace Feedback360.Controllers
{
    public class UserManagementController : Controller
    {
        BLUserManagement? _objblusermanagement = null;
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UserRegistration() 
        {
            try 
            {
              _objblusermanagement = new BLUserManagement();
              ViewBag.RoleDetails = _objblusermanagement.GetAllRoles();
              ViewBag.DesignationDetails = _objblusermanagement.GetAllDesignations();
            }
            catch(Exception ex)
            {

            }
            return View();
        }
        [HttpPost]
        public IActionResult UserRegistration(UserDetailsVM _userDetailsVM)
        {
            bool Save_result = false;
            try 
            { 
            _objblusermanagement = new BLUserManagement();
            ViewBag.RoleDetails = _objblusermanagement.GetAllRoles();
            ViewBag.DesignationDetails = _objblusermanagement.GetAllDesignations();
            
             Save_result =_objblusermanagement.saveUserDetails(_userDetailsVM);
            if (Save_result) ViewData["SaveStatus"] = "User Saved Successfully.";
            else ViewData["FailedStatus"] = "Save User Failed";
            }
            catch (Exception ex) 
            {
                ViewData["FailedStatus"] = ex.Message; 
            }
            return View();
        }
    }
}

Feedback360/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Feedback360</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Feedback360.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Feedback360</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Password" asp-action="ChangePassword">Change Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserManagement" asp-action="UserRegistration">User Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FeedBackSchedule" asp-action="FeedBackSchedule">FeedBack Schedule</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FeedBackSchedule" asp-action="Candidate_List">Candidate List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Feedback360 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>